### ISSUE TITLE
Error in test tracker: No module named 'data.utils'

### ISSUE THREAD

**Issue by foolhard** [neeharperi/LT3D#3]
Hello, 

Thanks for your great job. 
I am trying your test_tracker.py but failed. Error is 
`No module named 'data.utils'`

In your repo, I don't find the folder **data.utils**. 
Could you add your 'data.utils'? 

Best regards

**Comment by neeharperi** [comment]
Thanks for catching this! I've pushed an update to add this folder. Please let me know if you have further questions.

**Comment by foolhard** [comment]
Used the new code, fixed `data.utils `issue.
But, another error happen: no av2.evaluation.tracking module in av2-api v0.2.1. 

I try to install your [av2-api](https://github.com/neeharperi/av2-api.git) repo by `pip install -v -e .` , but failed. 
**How can I install your av2-api repo?** 

Below is the error info. 

```
  Running command Preparing editable metadata (pyproject.toml)

  Cargo, the Rust package manager, is not installed or is not on PATH.
  This package requires Rust and Cargo to compile extensions. Install it through
  the system's package manager or via https://rustup.rs/

  Checking for Rust toolchain....
  error: subprocess-exited-with-error
  
  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /dfs/data/miniconda/envs/lt3d/bin/python /dfs/data/miniconda/envs/lt3d/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_editable /tmp/tmpi06888ek
  cwd: /dfs/data/open_mmlab/av2-api
  Preparing editable metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by neeharperi** [comment]
It seems that you do not have Rust installed locally on your machine. One work around for this is to directly add  PATH_TO_REPO/av2-api/src to your PYTHONPATH in your bashrc

**Comment by foolhard** [comment]
I installed `rust` and it works. Thanks a lot.
