### ISSUE TITLE
How many samples are used for evaluation in End-to-End leaderboard?

### ISSUE THREAD

**Issue by foolhard** [neeharperi/LT3D#4]
Hello, 

I have question about the frames number used for evalution in End-to-End Forecasting Leaderboard.

1. Submission file of test set will contain 1/10 frames of a sequence according to 1Hz sampling rate, totally about ~2400 frames. Is it correct? 
2. Will all frames in the submission file be used to calculated the metrics?

Thanks.

**Comment by neeharperi** [comment]
1. Yes, this is correct
2. Yes, all frames in the submission file will be used to calculate metrics

**Comment by foolhard** [comment]
Thanks for kindly feedback.

**Comment by foolhard** [comment]
@neeharperi 
I am confused about the conversion code of forecast_labels by convert_forecast_labels() in av2.evaluation.eval as below:
`                for future_frame in frames[frame_idx + 1 : frame_idx + 1 + constants.NUM_TIMESTEPS]:`

Here you use **6 timesteps**, which means **future 6s** trajectories, because the dataset is 1Hz sampled. However, the competition requires to forecast **next 3s.** 

Is there anything misaligned here?

**Comment by foolhard** [comment]
Very clear. Then I understand how to subsample the sensor dataset for forecasting. 

Another quesiton about data:  
I find out that you extract the 1st frame of each sequence through [this line](https://github.com/neeharperi/LT3D/blob/43c182a36e436aaedb2d6a8de8e4ca412514128f/tools/data_converter/av2_converter.py#L374). Actually, 1st frame does not have the historical frames, thus it may decrease the model forecasting accuracy.
What do you think?

**Comment by neeharperi** [comment]
Yes, you are correct that the first frame does not have any history. I don't believe it will have a significant impact on forecasting accuracy. It is up to the method to determine the right way to address this case when there is no history.
