### ISSUE TITLE
Data preparetion of AV2 Dataset

### ISSUE THREAD

**Issue by Qingfeng800** [neeharperi/LT3D#7]
@neeharperi Hi,thanks for your excellent work.I have question about data preparetion ,in your readme,
`# For AV2 Dataset         
└── AV2_DATASET_ROOT
       ├── train       <-- train data and annotations
       ├── val         <-- val data and annotations
       ├── test        <-- test data
`
but when I download AV2 Dataset,there are four parts:
sensor, lidar, motion_forecasting and tbv.
And only motion_forecasting contains train,val  and test .But when I run `python tools/create_data.py av2 --root-path AV2_DATASET_ROOT --out-dir AV2_DATASET_ROOT/av2_mmdet3d_trainval --extra-tag av2 --max-sweeps 5` towards  motion_forecasting data, a bug appears:
 `FileNotFoundError: [Errno 2] Failed to open local file '/mnt/Hard_disk1/Datasets/Argoverse/for-detection/train/00a6ffc1-6ce9-3bc3-a060-6006e9893a1a/annotations.feather'. Detail: [errno 2] No such file or directory`
Could you introduce the preparetion of AV2 Dataset more specifically？Which part of AV2 Dataset  did you use?

**Comment by neeharperi** [comment]
We use the sensor dataset in our work. It should also have train/val/test folders as well
