### ISSUE TITLE
The result of argoverse2 competition 3D Object Detection cannot be evaluated

### ISSUE THREAD

**Issue by aotumanM** [neeharperi/LT3D#9]
The submitted file will remain in the state of submission and will not run. But there is no problem with tracking.
https://eval.ai/web/challenges/challenge-page/1710/submission

**Comment by neeharperi** [comment]
Hi @aotumanM, 
Thanks for pointing out this issue. I'll try to get this resolved ASAP. 

Thanks,
Neehar

**Comment by neeharperi** [comment]
The evaluation server is back up. Please feel free to keep submitting.

**Comment by aotumanM** [comment]
> The evaluation server is back up. Please feel free to keep submitting.
Thank you very much
